name: Bayesian_3DGS
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8
  - plyfile
  - python=3.9.23
  - pip=25.2
  - pytorch=2.1.2
  - torchaudio=2.1.2
  - torchvision=0.16.2
  - tqdm
  - websockets
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - submodules/fused-ssim
    - websockets